name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: "task-service"

        strategy:
            matrix:
                node-version: [15.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm test

    deploy:
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: asia-southeast1-docker.pkg.dev/otot-b-365611/otot-b-repo/task-service:latest
        defaults:
            run:
                working-directory: "task-service"

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Google Auth
              id: auth
              uses: google-github-actions/auth@v0
              with:
                  credentials_json: "${{secrets.GCP_CREDENTIALS}}"

            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v0

            - name: Authorise Docker push
              run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev

            - name: Build Docker image
              run: docker build . -t $IMAGE_NAME

            - name: Push Docker image
              run: docker push $IMAGE_NAME

            - name: Deploy Docker image
              run: gcloud run deploy task-service --image $IMAGE_NAME --region asia-southeast1 --platform managed --allow-unauthenticated --port 8000
